name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: themattrix/tox
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Package installation 
      run: apt-get update -y && apt-get install -y shellcheck
    - name: Shellcheck call tests
      run: shellcheck --shell=bash *.sh
    - name: Tox call tests
      run: tox -v
