name: tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Packages
        run: |
          apk add findutils git python3 py3-pip shellcheck
          pip3 install tox
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tox
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          tox -v
  linter-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "provision/"
